### ISSUE TITLE
This doesn't work anymore, getting 'Failed to fetch' error-message

### ISSUE THREAD

**Issue by mikeyfe6** [ChristopherBiscardi/serverless-todo-netlify-fauna-egghead#6]
This is the message that i'm getting, how to fix this? @ChristopherBiscardi

<img width="531" alt="Schermafbeelding 2021-12-11 om 00 43 20" src="https://user-images.githubusercontent.com/30863830/145654572-d42213c0-203d-4041-b408-cd05c3737dd1.png">

Repo: https://github.com/mikeyfe6/Afrodiasphere

**Comment by ChristopherBiscardi** [comment]
you're getting a CORS issue because you're hitting a production url on netlify from localhost, which is a different domain and thus is blocked. 


This is explained in the relevant video for the course on egghead: https://egghead.io/lessons/apollo-connecting-a-todo-app-to-a-serverless-graphql-api-using-apollo-client-and-solving-cors

**Comment by mikeyfe6** [comment]
Thank you for replying @ChristopherBiscardi but it still doesn't work, I already tested it from my production url also... there im getting a 502 error (See picture below). FYI; I completed your tutorial till the end and it worked like a charm back then. But after some updates I think there were some breaking changes that I just cannot figure out whats messing it up..

<img width="546" alt="Schermafbeelding 2021-12-17 om 00 44 15" src="https://user-images.githubusercontent.com/30863830/146472608-c69e311d-9d99-40d4-aa56-527963505cfa.png">
